---
- hosts: localhost
  become: yes

  tasks:

  - name: Update cache
    apt:
      name: "*"
      state: latest
      update_cache: yes
      force: yes


  - name: Install python dependencies
    apt:
      name:
        - python3-pip
        - python3
        - python3-virtualenv
        - virtualenv
        - python3-dev
        - git
      state: latest
    
  - name: Add a user on the raspi
    user:
      name: zaykos
      state: present

  - name: Copy the SSH private key to clone the repo because it's a private one
    copy:
      content: "/home/zaykos/.ssh/id_rsa"
      dest: "/home/zaykos/.ssh/"
      mode: 0600
  
  - name: Git clone the project repo 
    git:
        repo: "git@github.com:EpitechIT2020/T-YEP-600-PAR-6-1-finalproject-louis-auguste.dumas.git"
        dest: /home/zaykos/finalproject
        clone: yes
        update: yes
        force: yes
        accept_hostkey: yes

  - name: Change permissions
    file:
      path: /home/zaykos/finalproject/
      state: directory
      owner: "zaykos"
      recurse: true
  
  - name: Install soundAPI requirements
    pip:
      requirements: /home/zaykos/finalproject/Sound_API/requirements.txt
      virtualenv: /home/zaykos/finalproject/Sound_API/venv
      virtualenv_python: python3

  - name: Test the soundAPI if no errors
    command: python3 worker.py &
  
  