---
- hosts: rasp
  sudo: yes


  vars:
    - homeDir: /home/raspberry/my_app
    - appDir : app
    - repo: T-YEP-600-PAR-6-1-finalproject-louis-auguste.dumas
    - account: zaykos
    - privateKey: /Users/zaykos/.ssh/id_rsa


  tasks:
  - name: Install Packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - build-essential
      - npm
      - nodejs-legacy
      - git
      - mcrypt
      - nginx
      - curl

  - name: Create APP Directory
    file: path={{homeDir}}/{{appDir}} state=directory

  - name: Copy Private Key
    copy: src={{privateKey}} dest={{homeDir}} mode=0600

  - name: Git Clone Repo
    git: repo=git@github.com:{{account}}/{{repo}}.git dest={{homeDir}}/{{appDir}} update=yes force=yes accept_hostkey=yes key_file={{homeDir}}/id_rsa
    register: git_finished

  - name: Running NPM install
    npm: path={{homeDir}}/{{appDir}}
    register: npm_finished
    when: git_finished.changed

  - name: Start APP
    sudo_user: raspberry
    command: node --name app chdir={{homeDir}}/{{appDir}}/dist/index.js
    ignore_errors: yes
    when: npm_finished.changed
